<?php

namespace ContainerPYQixOe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dP6NpZ6.App\Entity\Habitant' shared service.
     *
     * @return \App\Entity\Habitant
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dP6NpZ6": it needs an instance of "App\\Entity\\Habitant" but this type has been excluded in "config/services.yaml".');
    }
}
