<?php

namespace ContainerPYQixOe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HabitationController' shared autowired service.
     *
     * @return \App\Controller\HabitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/HabitationController.php';

        $container->services['App\\Controller\\HabitationController'] = $instance = new \App\Controller\HabitationController(($container->privates['App\\Repository\\HabitationRepository'] ?? $container->load('getHabitationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\HabitationController', $container));

        return $instance;
    }
}
