<?php

namespace ContainerQuFsAAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HsnEzS6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hsnEzS6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hsnEzS6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'habitation' => ['privates', '.errored..service_locator.hsnEzS6.App\\Entity\\Habitation', NULL, 'Cannot autowire service ".service_locator.hsnEzS6": it needs an instance of "App\\Entity\\Habitation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'habitation' => 'App\\Entity\\Habitation',
        ]);
    }
}
