<?php

namespace ContainerQuFsAAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F6Ig9wi.App\Entity\Habitation' shared service.
     *
     * @return \App\Entity\Habitation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F6Ig9wi": it needs an instance of "App\\Entity\\Habitation" but this type has been excluded in "config/services.yaml".');
    }
}
