<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Habitation extends \App\Entity\Habitation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'SurfaceHabitable' => [parent::class, 'SurfaceHabitable', null],
        "\0".parent::class."\0".'TypeHabitation' => [parent::class, 'TypeHabitation', null],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'habitants' => [parent::class, 'habitants', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null],
        'SurfaceHabitable' => [parent::class, 'SurfaceHabitable', null],
        'TypeHabitation' => [parent::class, 'TypeHabitation', null],
        'adresse' => [parent::class, 'adresse', null],
        'habitants' => [parent::class, 'habitants', null],
        'id' => [parent::class, 'id', null],
        'ville' => [parent::class, 'ville', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
